services:
  my-api:
    image: complement-generator-api
    container_name: backend
    build:
      context: ./ComplimentGeneratorAPI
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
    ports:
      - "${API_PORT:-5000}:8080"
    depends_on:
      - mongodb
    networks:
      - compliment-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - compliment-net

  frontend:
    image: angular-app
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - my-api
    networks:
      - compliment-net
networks:
  compliment-net:
    driver: bridge
